import Header from '@/components/Header'
import '../styles/globals.css'
import { Inter } from 'next/font/google'
import Container from '@/components/Container'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: "Veronna's pizzaria",
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Container>
          <Header />
          {children}
          <Footer/>
        </Container>

      </body>
    </html>
  )
}
